### ISSUE TITLE
When retrieving movie details, the "origin_country" field is missing.

### ISSUE THREAD

**Issue by BenjaminSong90** [ChrisKruegerDev/tmdb-kotlin#146]
test api: https://developer.themoviedb.org/reference/movie-details

**Comment by ChrisKruegerDev** [comment]
@BenjaminSong90 The `origin_country` is in the production company object. There is no field `origin_country` in the movie details.

**Comment by BenjaminSong90** [comment]
this is movie detail info, the **origin_country** is in the detail


{
  "adult": false,
  "backdrop_path": "/cq9N64ucEtfIc3eMxNr1VzY9LH9.jpg",
  "belongs_to_collection": null,
  "budget": 40000000,
  "genres": [
    {
      "id": 18,
      "name": "Drama"
    }
  ],
  "homepage": "https://www.sonypictures.com/movies/thesocialnetwork",
  "id": 37799,
  "imdb_id": "tt1285016",
  "origin_country": [
    "US"
  ],
  "original_language": "en",
  "original_title": "The Social Network",
  "overview": "In 2003, Harvard undergrad and computer genius Mark Zuckerberg begins work on a new concept that eventually turns into the global social network known as Facebook. Six years later, he is one of the youngest billionaires ever, but Zuckerberg finds that his unprecedented success leads to both personal and legal complications when he ends up on the receiving end of two lawsuits, one involving his former friend.",
  "popularity": 47.351,
  "poster_path": "/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
  "production_companies": [
    {
      "id": 5,
      "logo_path": "/71BqEFAF4V3qjjMPCpLuyJFB9A.png",
      "name": "Columbia Pictures",
      "origin_country": "US"
    },
    {
      "id": 7295,
      "logo_path": "/62E1B91PxZw8q4KNkge5Qemo7EM.png",
      "name": "Relativity Media",
      "origin_country": "US"
    },
    {
      "id": 258,
      "logo_path": null,
      "name": "Scott Rudin Productions",
      "origin_country": "US"
    },
    {
      "id": 11370,
      "logo_path": null,
      "name": "Michael De Luca Productions",
      "origin_country": "US"
    },
    {
      "id": 7626,
      "logo_path": "/4839MGss4pPAalhqqYH1AD1CnEj.png",
      "name": "Trigger Street Productions",
      "origin_country": "US"
    }
  ],
  "production_countries": [
    {
      "iso_3166_1": "US",
      "name": "United States of America"
    }
  ],
  "release_date": "2010-10-01",
  "revenue": 224920315,
  "runtime": 121,
  "spoken_languages": [
    {
      "english_name": "English",
      "iso_639_1": "en",
      "name": "English"
    }
  ],
  "status": "Released",
  "tagline": "You don't get to 500 million friends without making a few enemies.",
  "title": "The Social Network",
  "video": false,
  "vote_average": 7.368,
  "vote_count": 11825
}

**Comment by ChrisKruegerDev** [comment]
Thanks. I will add the field

**Comment by ChrisKruegerDev** [comment]
Related to #151
